stages:
  - build
  - test

build_job:
  stage: build
  script:
    - echo "Building the project..."
    # Replace this with your actual build commands

test_job:
  stage: test
  script:
    - echo "Running tests..."
    # Replace this with your actual test commands
